version: '3.8'

services:

  static:
    image: static
    build: ./static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`localhost`)"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    deploy:
      replicas: 2
    expose:
      - "80"
  api:
    image: food-api
    build: ./food-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=7000"
    deploy:
      replicas: 3
    expose:
      - "7000"

  #config source: https://doc.traefik.io/traefik/getting-started/quick-start/
  reverse_proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock