version: '3.8'

services:

  static:
    image: static
    build: ./static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.static.tls=true"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - "80"
  api:
    image: food-api
    build: ./food-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=7000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.api.loadbalancer.sticky.cookie.name=peanut-butter-cookie"
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "7000"

  reverse_proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/